Created interfaces for Errors and added error property
payfunc/gracely pull request #51
Opened 2021-05-25 11:12 UTC by robinnedergard

2021-05-25 11:41 UTC, marcushanses requested changes

2021-05-25 11:41 UTC, marcushanses commented on server/index.ts
> +export { misconfigured, misconfigured as missconfigured } from "./misconfigured"
Misspelled misconfigured.

2021-05-25 15:25 UTC, marcushanses approved these changes

2021-05-26 07:28 UTC, nilssonemma requested changes

2021-05-26 07:28 UTC, nilssonemma commented on client/InvalidContent.ts
> +		return (
add content to typeguard

2021-05-26 09:19 UTC, nilssonemma approved these changes

2021-05-26 11:26 UTC, florianebmeier approved these changes

2021-05-26 13:47 UTC, marcushanses approved these changes

2021-05-27 20:36 UTC, fredrikbryntesson approved these changes

2021-05-27 20:36 UTC, merged